// Weekly broken link monitor — checks every URL in the sitemap returns 200.
// Creates a GitHub Issue if any are broken.
const https = require('https');
const fs    = require('fs');
const path  = require('path');

const PUBLIC = path.join(__dirname, '../../public');

function get(url) {
  return new Promise(resolve => {
    const req = https.get(url, {
      headers: { 'User-Agent': 'Letterhome-LinkChecker/1.0' }
    }, res => {
      res.resume();
      resolve({ url, status: res.statusCode });
    });
    req.on('error', e => resolve({ url, status: 'ERROR', note: e.message }));
    req.setTimeout(12000, () => { req.destroy(); resolve({ url, status: 'TIMEOUT' }); });
  });
}

function createIssue(token, repo, title, body) {
  return new Promise(resolve => {
    const payload = JSON.stringify({ title, body, labels: ['bug', 'broken-link'] });
    const [owner, name] = repo.split('/');
    const req = https.request({
      hostname: 'api.github.com',
      path: `/repos/${owner}/${name}/issues`,
      method: 'POST',
      headers: {
        'Authorization': `token ${token}`,
        'Content-Type': 'application/json',
        'User-Agent': 'Letterhome-Bot',
        'Content-Length': Buffer.byteLength(payload)
      }
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => { console.log('Issue:', JSON.parse(d).html_url); resolve(); });
    });
    req.on('error', e => { console.error('GitHub error:', e.message); resolve(); });
    req.write(payload);
    req.end();
  });
}

(async () => {
  const sitemap = fs.readFileSync(path.join(PUBLIC, 'sitemap.xml'), 'utf8');
  const urls    = [...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m => m[1]);

  console.log(`Checking ${urls.length} URLs...`);
  const broken = [];

  for (const url of urls) {
    const result = await get(url);
    const ok = [200, 301, 302, 303].includes(result.status);
    console.log(`${ok ? '✓' : '✗'} ${result.status} ${url}`);
    if (!ok) broken.push(result);
    await new Promise(r => setTimeout(r, 400));
  }

  if (!broken.length) { console.log('All links OK'); return; }

  const token = process.env.GITHUB_TOKEN;
  const repo  = process.env.REPO;

  const lines = broken.map(b =>
    `- \`${b.status}\` — ${b.url}${b.note ? ` *(${b.note})*` : ''}`
  ).join('\n');

  const issueBody = `## Broken links detected\n\n${lines}\n\n` +
    `*Checked ${urls.length} URLs from sitemap.xml — generated by weekly link monitor*`;

  if (token && repo) {
    await createIssue(token, repo,
      `Broken links — ${new Date().toISOString().split('T')[0]}`,
      issueBody
    );
  } else {
    console.error('Broken links found:\n', lines);
    process.exit(1);
  }
})();
