// Core Web Vitals monitor — checks PageSpeed Insights for key pages.
// Creates a GitHub Issue if any page scores below threshold.
const https = require('https');

const PAGES = [
  'https://letterhome.ca/',
  'https://letterhome.ca/how-to-send-a-letter-to-canada-from-abroad',
  'https://letterhome.ca/mail-a-letter-online',
  'https://letterhome.ca/send-a-letter-from-home',
  'https://letterhome.ca/guides',
];

const THRESHOLD = { performance: 80, lcp: 2500, cls: 0.1, fid: 100 };

function checkPage(url) {
  return new Promise(resolve => {
    const apiKey = process.env.PAGESPEED_API_KEY ? `&key=${process.env.PAGESPEED_API_KEY}` : '';
    const api = `https://www.googleapis.com/pagespeedonline/v5/runPagespeed` +
      `?url=${encodeURIComponent(url)}&strategy=mobile&category=performance${apiKey}`;
    const req = https.get(api, { headers: { 'User-Agent': 'Letterhome-CWVMonitor/1.0' } }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try {
          const json = JSON.parse(d);
          const cats  = json.lighthouseResult?.categories;
          const audits = json.lighthouseResult?.audits;
          const score = Math.round((cats?.performance?.score || 0) * 100);
          const lcp   = audits?.['largest-contentful-paint']?.numericValue || 0;
          const cls   = audits?.['cumulative-layout-shift']?.numericValue || 0;
          const tbt   = audits?.['total-blocking-time']?.numericValue || 0;
          resolve({ url, score, lcp: Math.round(lcp), cls: cls.toFixed(3), tbt: Math.round(tbt) });
        } catch { resolve({ url, score: 0, lcp: 0, cls: 0, tbt: 0, error: true }); }
      });
    });
    req.on('error', () => resolve({ url, score: 0, error: true }));
    req.setTimeout(30000, () => { req.destroy(); resolve({ url, score: 0, error: true }); });
  });
}

function createIssue(token, repo, title, body) {
  return new Promise(resolve => {
    const payload = JSON.stringify({ title, body, labels: ['performance', 'cwv'] });
    const [owner, name] = repo.split('/');
    const req = https.request({
      hostname: 'api.github.com',
      path: `/repos/${owner}/${name}/issues`,
      method: 'POST',
      headers: {
        'Authorization': `token ${token}`,
        'Content-Type': 'application/json',
        'User-Agent': 'Letterhome-Bot',
        'Content-Length': Buffer.byteLength(payload)
      }
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => { console.log('Issue:', JSON.parse(d).html_url); resolve(); });
    });
    req.on('error', e => { console.error(e.message); resolve(); });
    req.write(payload);
    req.end();
  });
}

(async () => {
  const results = [];
  for (const url of PAGES) {
    const r = await checkPage(url);
    const flag = r.error ? '⚠️' : r.score < THRESHOLD.performance ? '🔴' : '🟢';
    console.log(`${flag} ${r.score}/100  LCP:${r.lcp}ms  CLS:${r.cls}  TBT:${r.tbt}ms  ${r.url}`);
    results.push(r);
    await new Promise(res => setTimeout(res, 2000));
  }

  const failing = results.filter(r => r.error || r.score < THRESHOLD.performance);
  if (!failing.length) { console.log('All pages pass CWV thresholds'); return; }

  const rows = results.map(r => {
    const status = r.error ? '⚠️ error' : r.score < THRESHOLD.performance ? '🔴 fail' : '🟢 pass';
    return `| ${status} | ${r.score}/100 | ${r.lcp}ms | ${r.cls} | ${r.tbt}ms | ${r.url} |`;
  }).join('\n');

  const issueBody = `## Core Web Vitals — pages below ${THRESHOLD.performance}/100\n\n` +
    `| Status | Score | LCP | CLS | TBT | Page |\n` +
    `|--------|-------|-----|-----|-----|------|\n${rows}\n\n` +
    `**Targets:** Performance ≥${THRESHOLD.performance}, LCP <${THRESHOLD.lcp}ms, CLS <${THRESHOLD.cls}\n\n` +
    `*Checked on mobile via PageSpeed Insights — generated by weekly monitor*`;

  const token = process.env.GITHUB_TOKEN;
  const repo  = process.env.REPO;
  if (token && repo) {
    await createIssue(token, repo,
      `Core Web Vitals alert — ${new Date().toISOString().split('T')[0]}`,
      issueBody
    );
  } else {
    console.error('Failing pages:\n', rows);
  }
})();
