#!/usr/bin/env python3
"""Content for the new letter-mail guide pages. Consumed by gen-guides.py."""

REL_CRA = ("/cra-mail", "CRA Mail", "Tax returns and other CRA correspondence")
REL_OBJ = ("/cra-notice-of-objection", "CRA Notice of Objection", "Form T400A and the 90-day deadline")
REL_IRCC = ("/ircc-documents", "IRCC Documents", "Mail immigration documents from outside Canada")
REL_LTB = ("/ltb-forms", "All LTB Forms", "N4, N5, N9, N12, N13, L1 and more")
REL_N4 = ("/n4-notice", "N4 Notice", "Serve a non-payment notice by mail")
REL_N12 = ("/n12-notice", "N12 Notice", "Landlord's own use notice by mail")
REL_PRO = ("/for-professionals", "For Professionals", "Discount codes for accountants and paralegals")
REL_REG = ("/how-to-send-a-registered-letter-to-canada", "Registered Mail Basics", "How registered mail works with Letterhome")
REL_TRACK = ("/how-to-track-a-letter-to-canada", "Tracking a Letter", "How to follow your order after it's mailed")
REL_ABROAD = ("/how-to-send-a-letter-to-canada-from-abroad", "Sending Mail From Abroad", "The basics of mailing into Canada from anywhere")
REL_NORETURN = ("/send-a-letter-to-canada-without-a-return-address", "Sending Without a Return Address", "When and how to omit your return address")

GUIDES = [
    {
        "slug": "registered-mail-vs-xpresspost",
        "title": "Registered Mail vs Xpresspost vs Regular Mail in Canada | Letterhome",
        "meta_desc": "Regular lettermail, Xpresspost, and registered mail solve different problems. Here's the real difference in cost, speed, and proof, and how to send registered mail online from anywhere.",
        "service_name": "Mail Delivery Comparison",
        "breadcrumb": "Registered Mail vs Xpresspost vs Regular Mail",
        "eyebrow": "Canada Post Options",
        "h1_main": "Registered, Xpresspost, or regular.",
        "h1_em": "Here's the actual difference.",
        "hero_sub": "Speed and proof of delivery are two separate things, and Canada Post's naming doesn't make that obvious. Here's what each option actually buys you.",
        "cta_label": "Send a Letter →",
        "answer_box": "Regular lettermail is the cheapest and has no tracking. Xpresspost is faster with tracking, but no signature or proof of what was inside. Registered mail is the slowest of the three but the only one that gives you a signature on delivery and a paper trail if anyone ever disputes that you sent it.",
        "steps": [
            ("Regular lettermail", "No tracking, no delivery confirmation. Fine for anything where a lost letter is an inconvenience, not a problem. This is Letterhome's default at $10 CAD domestic."),
            ("Xpresspost", "Adds tracking and a faster delivery window, typically 1-2 business days within a region. What it doesn't add is proof of who signed for it, useful for speed, not for evidence."),
            ("Registered mail", "Slower than Xpresspost, but the only option with a signature on file and a tracking number that holds up as proof of delivery. This is what you want for anything involving a legal deadline, an inheritance, or a dispute."),
        ],
        "warn": None,
        "sections": [
            ("When registered mail actually matters", [
                "If a court, tribunal, or government body needs proof that a specific document arrived, on a specific date, registered mail is the one that gives you that. A tracking number alone from Xpresspost shows a parcel moved, not necessarily what was inside it.",
                "Eviction notices, CRA objections, legal notices, and anything with a hard deadline are the common cases. A birthday card is not.",
            ]),
            ("Sending registered mail without going to a post office", [
                "You can add registered mail to any Letterhome order at checkout for $27.50. Upload your letter, check the box, and we handle the trip to Canada Post. A tracking number is emailed to you within 2-3 business days.",
            ]),
        ],
        "faq": [
            ("Is Xpresspost the same as registered mail?", "No. Xpresspost is a speed and tracking product. Registered mail is a proof-of-delivery product with a signature requirement. They can overlap in transit time, but they solve different problems."),
            ("Do I need registered mail for a CRA objection?", "It's not legally required, but it gives you a signature and tracking number as proof the CRA received it, which matters if the objection is ever disputed on timing. See our <a href=\"/cra-notice-of-objection\">CRA Notice of Objection guide</a> for the deadline itself."),
            ("How much does registered mail cost with Letterhome?", "$27.50 CAD added to your base letter price, for tracked, signed-for delivery within Canada."),
            ("Can I add registered mail to an international letter?", "Registered mail through Letterhome is for domestic Canadian addresses. For international tracked mail, email support@letterhome.ca before ordering."),
        ],
        "related": [REL_REG, REL_OBJ, REL_LTB, REL_TRACK],
        "cta_h2": "Need proof it arrived?",
        "cta_p": "Add registered mail at checkout for $27.50, tracked and signed for.",
        "cta_final": "Send With Registered Mail →",
    },
    {
        "slug": "proof-of-mailing",
        "title": "How to Keep Proof You Sent an Important Letter | Letterhome",
        "meta_desc": "A dated mailing confirmation is often all the proof you need. Here's what actually counts as proof you sent a letter in Canada, and how to get it without a trip to the post office.",
        "service_name": "Proof of Mailing",
        "breadcrumb": "How to Keep Proof You Sent a Letter",
        "eyebrow": "Records & Evidence",
        "h1_main": "\"How do I prove I sent it?\"",
        "h1_em": "Three things, no extra paperwork.",
        "hero_sub": "A dated copy of the letter, a mailing confirmation showing the date and address, and a simple log of when you sent what. That's the whole answer.",
        "cta_label": "Send a Letter →",
        "answer_box": "You don't need a lawyer's file system. A copy of what you sent, a confirmation with the mailing date, and knowing where that confirmation lives is enough proof for almost every situation where it comes up later.",
        "steps": [
            ("Keep a copy of the letter itself", "Whatever you upload to be mailed, save it. If a dispute ever comes down to what the letter actually said, having the exact file beats trying to reconstruct it from memory."),
            ("Get a confirmation with the mailing date", "Every Letterhome order sends a confirmation email showing the date your letter was mailed, the recipient, and the order number. That date is your evidence of when it left your hands, not when it arrives."),
            ("Keep the confirmation somewhere you'll find it", "A dedicated email folder or a single starred message works. The order stays in your account under order history too, so it isn't only in your inbox."),
        ],
        "warn": ("Not the same as registered mail:", "a mailing confirmation proves you sent something on a date. It doesn't prove what was received or that it arrived. If you need that level of proof, see <a href=\"/registered-mail-vs-xpresspost\">registered mail</a> instead."),
        "sections": [
            ("Why the mailing date is what matters", [
                "For CRA filings, LTB notices, and most deadline-driven mail, what counts legally is the date something was mailed, not the date it's read. That's exactly what a mailing confirmation documents.",
            ]),
        ],
        "faq": [
            ("Does a Letterhome confirmation email count as legal proof?", "It documents the date you placed the order and the recipient address, which is the same kind of record a Canada Post receipt provides. Whether it's sufficient for your specific situation depends on the body you're dealing with, when in doubt use registered mail for a signature."),
            ("What if I need proof of delivery, not just proof of mailing?", "That needs registered mail or Xpresspost with tracking. A standard mailing confirmation only proves the mailing date, not arrival."),
            ("Can I get a copy of an old order confirmation?", "Yes, log into your account and check order history, or email support@letterhome.ca with your order number."),
            ("How long do you keep order records?", "See our <a href=\"/privacy\">privacy policy</a> for how long order records and letter content are retained."),
        ],
        "related": [REL_REG, REL_TRACK, REL_LTB, REL_OBJ],
        "cta_h2": "Send it with a paper trail.",
        "cta_p": "Every order comes with a dated confirmation email, no extra step required.",
        "cta_final": "Send a Letter, $10 CAD →",
    },
    {
        "slug": "government-forms-that-require-mail",
        "title": "Which Canadian Government Forms Still Require Mail in 2026 | Letterhome",
        "meta_desc": "More than a dozen common Canadian government forms still have to go by paper mail in 2026. Here's the issuer-by-issuer list of which ones, and how to mail them from anywhere.",
        "service_name": "Government Forms Mailing",
        "breadcrumb": "Canadian Government Forms That Require Mail",
        "eyebrow": "Federal & Provincial Forms",
        "h1_main": "Still paper-only in 2026.",
        "h1_em": "Here's the actual list.",
        "hero_sub": "Online portals cover a lot now, but a specific set of Canadian government forms still has to arrive by mail. If you're not in Canada when one of these comes up, this is what you're dealing with.",
        "cta_label": "Send a Letter →",
        "answer_box": "CRA objections, several IRCC applications, CPP and OAS applications in specific situations, and most provincial landlord-tenant forms still require, or strongly prefer, paper by mail. Each has its own form number and mailing address.",
        "steps": [
            ("Confirm the form still requires mail", "Some of these have partial online options depending on your account access level. Check the issuer's own page for your specific form before assuming mail is mandatory."),
            ("Fill it out and export to PDF", "Sign where required. Most of these forms are rejected or delayed for a missing signature more often than any other reason."),
            ("Mail it from wherever you are", "Upload the PDF at Letterhome with the correct mailing address, and it goes out from inside Canada within one business day."),
        ],
        "warn": ("Addresses change:", "always confirm the current mailing address on the issuer's own site before ordering. Some forms in this list use a regional address, not a single national one."),
        "sections": [
            ("Federal forms that still require mail", [
                "<strong>CRA Notice of Objection (T400A)</strong>: disputing an assessment. See our <a href=\"/cra-notice-of-objection\">full guide</a>.",
                "<strong>CPP Retirement Pension (ISP1000)</strong>: in some cases faster or necessary by mail. <a href=\"/cpp-application-by-mail\">Guide here</a>.",
                "<strong>OAS and GIS (ISP3550)</strong>: required by mail if you're not auto-enrolled. <a href=\"/oas-gis-application-by-mail\">Guide here</a>.",
                "<strong>Canada Child Benefit (RC66)</strong>: mail-only for newcomers without a prior tax filing history. <a href=\"/canada-child-benefit-by-mail\">Guide here</a>.",
                "<strong>PR Card Renewal (IMM 5444)</strong>: paper option alongside the online portal. <a href=\"/renew-pr-card-by-mail\">Guide here</a>.",
                "<strong>Canadian Citizenship Application (CIT 0002)</strong>: mailed to a single processing centre. <a href=\"/canadian-citizenship-application-by-mail\">Guide here</a>.",
            ]),
            ("Provincial forms that still require mail", [
                "Ontario Landlord and Tenant Board notices (N4, N9, N12, and others) are commonly served by mail, especially when the landlord or tenant isn't reachable in person. See our <a href=\"/ltb-forms\">LTB forms guide</a>.",
            ]),
        ],
        "faq": [
            ("Why do these still require paper in 2026?", "Signature requirements, identity verification, and legislation written before online submission existed are the usual reasons. Some are slowly moving online, but not on a fixed timeline."),
            ("What if I mail the wrong form to the wrong address?", "It usually just means delay while it's redirected internally, or in stricter cases, rejection and a request to resubmit. Confirm the address before mailing."),
            ("Can I mail more than one form in the same envelope?", "Only if the issuer allows combined submissions, check the specific form's instructions. When in doubt, mail them as separate orders to be safe."),
            ("Do you keep this list updated?", "We review it periodically, but government requirements do change. Always confirm on the issuer's own site before a deadline-sensitive mailing."),
        ],
        "related": [REL_OBJ, REL_CRA, REL_IRCC, REL_LTB],
        "cta_h2": "Whatever the form, we'll mail it.",
        "cta_p": "Upload your PDF, we print and mail it from inside Canada, next business day.",
        "cta_final": "Send a Letter, $10 CAD →",
    },
    {
        "slug": "n9-notice",
        "title": "Mail an N9 Notice to End Your Tenancy in Ontario | Letterhome",
        "meta_desc": "Moving out and need to give your landlord written notice? Here's how to fill out and mail Ontario's N9 form, the 60-day rule, and how to send it from anywhere.",
        "service_name": "N9 Notice Mailing",
        "breadcrumb": "N9 Notice Mailing",
        "eyebrow": "Ontario Tenant Notices",
        "h1_main": "Give notice with Form N9,",
        "h1_em": "from anywhere you're moving to.",
        "hero_sub": "Ontario tenants ending a monthly tenancy owe their landlord 60 days' written notice on Form N9. Upload it and we mail it from inside Canada, next business day.",
        "cta_label": "Mail My N9 Now →",
        "answer_box": "The N9 is the tenant's own Notice to End a Tenancy. For a monthly tenancy you owe 60 days' notice, ending on the last day of a rental period. It has to be in writing and delivered to your landlord, mail is an accepted method.",
        "steps": [
            ("Download and fill out Form N9", "Get it free from the <a href=\"https://tribunalsontario.ca/ltb/forms/\" target=\"_blank\" rel=\"noopener\">Landlord and Tenant Board</a>. Enter the termination date, at least 60 days out and matching the end of a rental period."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter your landlord's mailing address as the recipient, and attach your completed N9 PDF."),
            ("We mail it the next business day", "Your N9 goes out via Canada Post with a valid Canadian mailing date. Add a few days for delivery when you calculate your 60-day window."),
        ],
        "warn": ("This isn't legal advice.", "Rules on termination dates and required notice periods can be specific to your tenancy type. Confirm the current requirements at <a href=\"https://tribunalsontario.ca\" target=\"_blank\" rel=\"noopener\">tribunalsontario.ca</a> before filing."),
        "sections": [
            ("Getting the termination date right", [
                "The N9's termination date has to fall on the last day of a rental period, the day before rent is next due, and be at least 60 days after your landlord receives the notice. Mailing adds delivery time on top of that, so mail early rather than exactly at 60 days.",
            ]),
        ],
        "faq": [
            ("How much notice do I owe on a monthly tenancy?", "60 days, ending on the last day of a rental period. Different rules apply to fixed-term leases and other tenancy types, check the LTB's guidance for your situation."),
            ("Can I serve the N9 by mail?", "Yes. Mail is an accepted method of delivering an N9 to your landlord, but factor in delivery time when calculating your termination date."),
            ("Do I need my landlord's exact mailing address?", "Yes, use the address you normally send rent payments or notices to, or the address on your lease."),
            ("How much does it cost?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing via Canada Post."),
        ],
        "related": [REL_LTB, REL_N4, REL_N12],
        "cta_h2": "Ready to give notice?",
        "cta_p": "Upload your N9 and we'll have it in the mail by tomorrow.",
        "cta_final": "Mail My N9, $10 CAD →",
    },
    {
        "slug": "renew-pr-card-by-mail",
        "title": "Renew Your PR Card by Mail in Canada (IMM 5444) | Letterhome",
        "meta_desc": "Renewing a permanent resident card still has a paper option alongside the online portal. Here's how to build the IMM 5444 package and mail it from anywhere.",
        "service_name": "PR Card Renewal Mailing",
        "breadcrumb": "PR Card Renewal by Mail",
        "eyebrow": "IRCC Immigration Mail",
        "h1_main": "Renew your PR card,",
        "h1_em": "even if you're not in Canada right now.",
        "hero_sub": "The PR card renewal application (IMM 5444) can be filed on paper. Upload your package and we mail it from inside Canada, next business day.",
        "cta_label": "Mail My PR Card Renewal →",
        "answer_box": "Most people renew online, but the paper IMM 5444 route still exists and is sometimes the more reliable path if your online account has an issue or you're outside Canada without stable access.",
        "steps": [
            ("Prepare the IMM 5444 application", "Download the current kit and instructions from <a href=\"https://www.canada.ca/en/immigration-refugees-citizenship/services/new-immigrants/pr-card/apply-renew.html\" target=\"_blank\" rel=\"noopener\">canada.ca</a>. Include photos meeting the specification and any required supporting documents."),
            ("Confirm the current mailing address", "IRCC mailing addresses for paper applications are listed on the same page and can change, verify it before sending rather than reusing an old address."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the IRCC processing address as the recipient, and attach your completed package."),
            ("We mail it the next business day", "Your application goes out via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": ("Meet the residency requirement first:", "PR card renewal has its own physical presence requirement, separate from citizenship. Confirm you qualify before applying, IRCC's page covers the current rule."),
        "sections": [
            ("Processing times", [
                "Paper applications generally take longer to process than online ones. Check <a href=\"/ircc-processing-times\">current IRCC processing times</a> before deciding which route fits your timeline.",
            ]),
        ],
        "faq": [
            ("Can I renew my PR card from outside Canada?", "Renewal generally requires meeting a physical presence requirement in Canada. Confirm your eligibility on IRCC's site before applying, this guide only covers how to mail the completed package."),
            ("Is paper slower than the online application?", "Usually yes. Paper applications typically take longer to process. Use paper when the online portal isn't a workable option for you."),
            ("What photos do I need?", "IRCC has a specific photo specification for PR card applications, listed on their page. Photos that don't meet spec are a common cause of returned applications."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing. IRCC application fees are separate and paid directly to IRCC."),
        ],
        "related": [REL_IRCC, ("/ircc-processing-times", "IRCC Processing Times", "Current wait times by application type"), REL_OBJ],
        "cta_h2": "Ready to mail your renewal?",
        "cta_p": "Upload your IMM 5444 package and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My PR Renewal, $10 CAD →",
    },
    {
        "slug": "canadian-citizenship-application-by-mail",
        "title": "Mail Your Canadian Citizenship Application (CIT 0002) | Letterhome",
        "meta_desc": "Applying for Canadian citizenship still means mailing a paper package to a single processing centre. Here's how to build the CIT 0002 application and mail it from anywhere.",
        "service_name": "Citizenship Application Mailing",
        "breadcrumb": "Citizenship Application by Mail",
        "eyebrow": "IRCC Immigration Mail",
        "h1_main": "Mail your citizenship application,",
        "h1_em": "wherever you're applying from.",
        "hero_sub": "The Application for Canadian Citizenship (CIT 0002) is submitted by mail to a single IRCC processing centre. Upload your package and we mail it from inside Canada, next business day.",
        "cta_label": "Mail My Citizenship Application →",
        "answer_box": "Count your physical presence days first, most adult applicants need 1,095 days within the five years before applying. Once your package is complete, it's mailed as a single paper submission, not filed online.",
        "steps": [
            ("Confirm you meet the presence requirement", "Use IRCC's physical presence calculator to confirm your days before spending time on the rest of the package."),
            ("Build the CIT 0002 package", "Include the application form, proof of status, language test results if required, and the current application fee receipt. IRCC's document checklist for your situation lists everything needed."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the current IRCC citizenship processing address as the recipient, and attach your complete PDF package."),
            ("We mail it the next business day", "Your application is mailed via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": ("Missing documents are the most common delay.", "Use IRCC's document checklist for your specific situation before mailing, an incomplete package is often returned rather than processed."),
        "sections": [],
        "faq": [
            ("How many days of physical presence do I need?", "Most adult applicants need 1,095 days within the five years immediately before applying. Some time outside Canada can still count under specific rules, check IRCC's calculator for your exact number."),
            ("Can I apply from outside Canada?", "The application is mailed to a Canadian processing address regardless of where you are when you submit it, which is exactly the situation Letterhome is built for."),
            ("How long does processing take?", "Check <a href=\"/ircc-processing-times\">current IRCC processing times</a>, citizenship applications can take a significant number of months."),
            ("How much does it cost to mail?", "$10 CAD for the mailing itself. IRCC's application and right of citizenship fees are separate and paid directly to IRCC."),
        ],
        "related": [REL_IRCC, ("/ircc-processing-times", "IRCC Processing Times", "Current wait times by application type"), ("/renew-pr-card-by-mail", "PR Card Renewal", "Mail your PR card renewal package")],
        "cta_h2": "Ready to mail your application?",
        "cta_p": "Upload your CIT 0002 package and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Application, $10 CAD →",
    },
    {
        "slug": "cpp-application-by-mail",
        "title": "Apply for CPP Retirement Pension by Mail (ISP1000) | Letterhome",
        "meta_desc": "You can start CPP as early as 60 or wait as late as 70 for a larger payment. Here's how to apply by mail with Form ISP1000, and how to mail it from anywhere.",
        "service_name": "CPP Application Mailing",
        "breadcrumb": "CPP Application by Mail",
        "eyebrow": "Service Canada Mail",
        "h1_main": "Apply for CPP by mail,",
        "h1_em": "on your own timeline.",
        "hero_sub": "The CPP Retirement Pension application (ISP1000) can be mailed to Service Canada. Upload it and we mail it from inside Canada, next business day.",
        "cta_label": "Mail My CPP Application →",
        "answer_box": "You can start CPP as early as age 60 at a reduced monthly amount, or as late as 70 for a larger one. There's no single right age, it depends on your own finances and health expectations. The application itself is the same either way.",
        "steps": [
            ("Decide when you want payments to start", "You can apply up to 12 months before you want your first payment. Starting earlier reduces the monthly amount, starting later increases it, up to age 70."),
            ("Fill out Form ISP1000", "Download the current form from <a href=\"https://www.canada.ca/en/services/benefits/publicpensions/cpp/pension.html\" target=\"_blank\" rel=\"noopener\">canada.ca</a>. Include your Social Insurance Number and banking details for direct deposit."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the Service Canada mailing address for your region, and attach your completed form."),
            ("We mail it the next business day", "Your application goes out via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": None,
        "sections": [],
        "faq": [
            ("What's the earliest I can start CPP?", "Age 60, at a permanently reduced monthly amount compared to starting at 65."),
            ("Is it better to wait until 70?", "Waiting increases your monthly amount permanently, up to age 70. Whether that's the better choice depends on your own retirement plans, this isn't financial advice, consider speaking with an advisor for your specific situation."),
            ("Can I apply from outside Canada?", "Yes, CPP is available to Canadians living abroad who qualify. The application is mailed to a Canadian Service Canada address regardless of where you're living."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/oas-gis-application-by-mail", "OAS and GIS by Mail", "Apply for Old Age Security and the Guaranteed Income Supplement"), REL_CRA, REL_OBJ],
        "cta_h2": "Ready to apply?",
        "cta_p": "Upload your ISP1000 and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My CPP Application, $10 CAD →",
    },
    {
        "slug": "oas-gis-application-by-mail",
        "title": "Apply for OAS and GIS by Mail (Form ISP3550) | Letterhome",
        "meta_desc": "Old Age Security doesn't always arrive automatically, and the Guaranteed Income Supplement is money many low-income seniors leave unclaimed. Here's how to apply for both by mail.",
        "service_name": "OAS and GIS Application Mailing",
        "breadcrumb": "OAS and GIS Application by Mail",
        "eyebrow": "Service Canada Mail",
        "h1_main": "Apply for OAS and GIS,",
        "h1_em": "don't assume it's automatic.",
        "hero_sub": "Some seniors are auto-enrolled for Old Age Security, many aren't. The Guaranteed Income Supplement is separate and needs its own application. Form ISP3550 covers both, mailed to Service Canada.",
        "cta_label": "Mail My OAS/GIS Application →",
        "answer_box": "If you haven't received a letter confirming automatic enrollment for OAS around age 64, don't assume it's coming. GIS, the supplement for lower-income seniors, is never automatic, it always requires an application.",
        "steps": [
            ("Check whether you're already auto-enrolled", "Service Canada sends a letter to most people around age 64 confirming automatic OAS enrollment. If you never received one, you need to apply."),
            ("Fill out Form ISP3550", "This combined form covers both OAS and GIS applications. Get the current version from <a href=\"https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security.html\" target=\"_blank\" rel=\"noopener\">canada.ca</a>."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the Service Canada mailing address for your region, and attach your completed form."),
            ("We mail it the next business day", "Your application goes out via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": None,
        "sections": [],
        "faq": [
            ("How do I know if I'm already enrolled for OAS?", "Service Canada mails a confirmation letter to most eligible people around age 64. No letter usually means you need to apply."),
            ("Is GIS automatic if I'm already getting OAS?", "No. GIS always requires a separate application, even if your OAS is automatic, and it's income-tested, reapplication or renewal may be needed based on your tax filing."),
            ("Can I apply from outside Canada?", "OAS has its own residency rules for people living abroad, different from GIS which generally requires Canadian residency. Confirm your eligibility on Service Canada's page before applying."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/cpp-application-by-mail", "CPP Application by Mail", "Apply for the CPP Retirement Pension"), ("/canada-child-benefit-by-mail", "Canada Child Benefit by Mail", "Apply for the CCB with Form RC66"), REL_CRA],
        "cta_h2": "Ready to apply?",
        "cta_p": "Upload your ISP3550 and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Application, $10 CAD →",
    },
    {
        "slug": "canada-child-benefit-by-mail",
        "title": "Apply for the Canada Child Benefit by Mail (Form RC66) | Letterhome",
        "meta_desc": "The Canada Child Benefit isn't automatic, especially for newcomers without a prior tax filing history. Here's how to apply by mail with Form RC66, and RC66SCH if you're new to Canada.",
        "service_name": "Canada Child Benefit Application Mailing",
        "breadcrumb": "Canada Child Benefit by Mail",
        "eyebrow": "CRA Family Benefits",
        "h1_main": "Apply for the Canada Child Benefit,",
        "h1_em": "even without a Canadian tax history.",
        "hero_sub": "Form RC66 applies for the CCB. Newcomers without a prior tax filing add Form RC66SCH. Both mail to the CRA, and we can send them from anywhere.",
        "cta_label": "Mail My RC66 →",
        "answer_box": "The CCB is money the CRA pays monthly to eligible families, but it isn't automatic unless you've already filed taxes with your child's information on record. Newcomers to Canada in particular need to apply directly.",
        "steps": [
            ("Fill out Form RC66", "Get the current version from <a href=\"https://www.canada.ca/en/revenue-agency/services/forms-publications/forms/rc66.html\" target=\"_blank\" rel=\"noopener\">canada.ca</a>. Include your child's proof of birth if the CRA doesn't already have it on file."),
            ("Add Form RC66SCH if you're new to Canada", "This status in Canada schedule is required if you or your spouse became a resident, or are a newcomer, within the last two years."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter your CRA tax centre address, and attach both forms as PDFs."),
            ("We mail it the next business day", "Your application goes out via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": None,
        "sections": [],
        "faq": [
            ("Do I need to apply if I already file taxes in Canada?", "Often the CRA can pick up eligibility automatically from a birth registration or prior return, but if you're not receiving it and believe you're eligible, applying directly with RC66 is the reliable path."),
            ("What is RC66SCH for?", "It's a supplementary schedule for people new to Canada, confirming immigration and residency status details the CRA needs alongside the main RC66."),
            ("How long does it take to process?", "Processing times vary, check the current estimate on the CRA's CCB page before assuming a specific timeline."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [REL_CRA, REL_OBJ, ("/oas-gis-application-by-mail", "OAS and GIS by Mail", "Apply for Old Age Security and the Guaranteed Income Supplement")],
        "cta_h2": "Ready to apply?",
        "cta_p": "Upload your RC66 and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Application, $10 CAD →",
    },
    {
        "slug": "demand-letter-unpaid-invoice",
        "title": "Write and Send a Demand Letter for an Unpaid Invoice | Letterhome",
        "meta_desc": "Reminders being ignored? A firm, mailed demand letter is usually what gets an overdue invoice paid, and it's the step small claims court expects you to have taken first.",
        "service_name": "Demand Letter Mailing",
        "breadcrumb": "Demand Letter for an Unpaid Invoice",
        "eyebrow": "Business Correspondence",
        "h1_main": "The reminders didn't work.",
        "h1_em": "A demand letter is the next step.",
        "hero_sub": "A mailed demand letter puts an overdue invoice on the record and is usually a precondition small claims court expects. Here's what to include and how to send it.",
        "cta_label": "Send a Demand Letter →",
        "answer_box": "A demand letter states what's owed, the deadline to pay it, and what happens next if it isn't. Sending it by mail, not just email, is what makes it look, and function, as a formal step rather than another reminder.",
        "steps": [
            ("State the facts plainly", "Invoice number, amount owed, original due date, and any prior reminders sent. No need for aggressive language, specificity does the work."),
            ("Set a firm deadline", "10 to 14 days is standard. State clearly what happens if the deadline passes, typically referral to collections or small claims court."),
            ("Mail it, don't just email it", "A physical letter signals seriousness in a way email doesn't, and gives you a mailing date on record if this ends up in court."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the debtor's mailing address, and attach your signed letter."),
        ],
        "warn": ("This isn't legal advice.", "Requirements for demand letters before small claims filing vary by province. Check your province's small claims court process before relying on this as your only pre-filing step."),
        "sections": [],
        "faq": [
            ("Do I need a lawyer to send a demand letter?", "No, you can write and send one yourself. A lawyer's letterhead can add weight in some cases, but a clear, specific letter from you is often enough."),
            ("Is a demand letter required before small claims court?", "Many provinces expect or require you to have attempted to resolve the debt directly first, and a mailed demand letter documents that attempt. Check your specific province's rules."),
            ("What if they still don't pay?", "Your next steps are typically small claims court or a collections agency, depending on the amount and your preference. Keep your demand letter and mailing confirmation as part of your file either way."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/security-deposit-demand-letter", "Security Deposit Demand Letter", "Get your deposit back with a written demand"), REL_LTB, ("/dispute-credit-report-error", "Dispute a Credit Report Error", "Fix an incorrect item on Equifax or TransUnion")],
        "cta_h2": "Ready to send it?",
        "cta_p": "Upload your demand letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Letter, $10 CAD →",
    },
    {
        "slug": "security-deposit-demand-letter",
        "title": "Get Your Security Deposit Back With a Demand Letter | Letterhome",
        "meta_desc": "Landlord rules and deadlines for returning a security or last month's rent deposit vary by province. Here's how to write and mail a demand letter to get it back.",
        "service_name": "Security Deposit Demand Letter Mailing",
        "breadcrumb": "Security Deposit Demand Letter",
        "eyebrow": "Tenant Correspondence",
        "h1_main": "Your deposit is overdue.",
        "h1_em": "Put the demand in writing.",
        "hero_sub": "Deposit rules differ by province, but a clear, mailed demand letter is the common first step everywhere. Here's what to include and how to send it.",
        "cta_label": "Send a Demand Letter →",
        "answer_box": "State the amount, the date you moved out, and the deadline your province gives landlords to return it or provide an itemized reason for withholding it. A dated, mailed letter is your record if this goes further.",
        "steps": [
            ("Check your province's deposit rules", "What counts as a deposit, and the deadline to return it, varies. Ontario's last month's rent deposit rules differ from a security or damage deposit in other provinces, confirm yours before writing."),
            ("Write the letter", "State your move-out date, forwarding address, amount owed, and the deadline you're giving, referencing your province's specific rule if there is one."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter your former landlord's address, and attach your signed letter."),
            ("We mail it the next business day", "Your letter goes out via Canada Post with a valid Canadian mailing date, your record if you need to escalate to a tenancy board."),
        ],
        "warn": ("This isn't legal advice.", "Deposit rules differ meaningfully by province. Check your provincial landlord-tenant board's current guidance before sending."),
        "sections": [],
        "faq": [
            ("How long does a landlord have to return a deposit?", "This varies by province and by whether deductions are being claimed. Check your provincial tenancy board's current rule rather than assuming a fixed number of days."),
            ("What if my landlord ignores the letter?", "Most provinces have a landlord-tenant board or tribunal where you can file a claim. Your mailed demand letter and its mailing date become part of that record."),
            ("Do I need to send this by mail instead of text or email?", "A mailed letter creates a clearer, dated record than a text thread, which matters if this goes to a tribunal. It isn't always required, but it's the stronger record."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [REL_LTB, REL_N4, ("/demand-letter-unpaid-invoice", "Demand Letter for an Unpaid Invoice", "Get an overdue invoice paid")],
        "cta_h2": "Ready to send it?",
        "cta_p": "Upload your demand letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Letter, $10 CAD →",
    },
    {
        "slug": "cease-and-desist-letter",
        "title": "Write and Send a Cease and Desist Letter in Canada | Letterhome",
        "meta_desc": "Unwanted calls, harassment, or someone still using your work without permission. Here's how to write a cease and desist letter in Canada and mail it properly.",
        "service_name": "Cease and Desist Letter Mailing",
        "breadcrumb": "Cease and Desist Letter",
        "eyebrow": "Legal Correspondence",
        "h1_main": "Put it in writing:",
        "h1_em": "stop, or this escalates.",
        "hero_sub": "A cease and desist letter formally documents the conduct, states what has to stop, and puts the other side on notice before you escalate. Here's how to write and mail one.",
        "cta_label": "Send a Cease and Desist Letter →",
        "answer_box": "There's no official form. The letter needs to describe the specific conduct, the date it needs to stop by, and what you'll do if it doesn't. Sending it by mail, with a copy kept, is what makes it usable evidence later.",
        "steps": [
            ("Describe the conduct specifically", "Dates, what happened, and why it's a problem, whether that's harassment, unauthorized use of your work, or a contract breach. Vague language weakens the letter."),
            ("State exactly what you want to stop", "Be specific about the behaviour, not just \"stop bothering me.\" A specific demand is easier to prove was ignored if this escalates."),
            ("Set a deadline and a consequence", "A reasonable deadline, and what happens after it, whether that's a complaint, a report, or legal action."),
            ("Mail it and keep a copy", "Upload it at Letterhome with the other party's mailing address. Keep the letter and your mailing confirmation together."),
        ],
        "warn": ("This isn't legal advice.", "For serious harassment, IP infringement, or anything with real legal stakes, consider having a lawyer review the letter, or send it on your behalf, before mailing."),
        "sections": [],
        "faq": [
            ("Does a cease and desist letter have legal force on its own?", "Not automatically, it's a formal warning, not a court order. Its value is in documenting that you gave clear notice before escalating."),
            ("Can I write one myself, or do I need a lawyer?", "You can write and send one yourself. A lawyer's letter can carry more weight in serious matters, but a clear, specific letter from you is a legitimate first step."),
            ("What if they ignore it?", "Depending on the conduct, next steps might include a formal complaint, a report to a relevant authority, or legal action. Keep your letter and mailing confirmation as part of that record."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/respond-to-debt-collection-letter", "Responding to a Debt Collection Letter", "The calm, correct way to respond"), ("/demand-letter-unpaid-invoice", "Demand Letter for an Unpaid Invoice", "Get an overdue invoice paid"), REL_LTB],
        "cta_h2": "Ready to send it?",
        "cta_p": "Upload your letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Letter, $10 CAD →",
    },
    {
        "slug": "respond-to-debt-collection-letter",
        "title": "How to Respond to a Debt Collection Letter in Canada | Letterhome",
        "meta_desc": "A collection letter demanding a sum you may not recognize doesn't mean pay immediately or ignore it entirely. Here's the calm, correct way to respond, in writing.",
        "service_name": "Debt Collection Response Mailing",
        "breadcrumb": "Responding to a Debt Collection Letter",
        "eyebrow": "Consumer Correspondence",
        "h1_main": "A collection letter arrived.",
        "h1_em": "Neither panic-pay nor ignore it.",
        "hero_sub": "The two common instincts, paying immediately or ignoring it, are both risky. A written response asking for verification is usually the correct first move.",
        "cta_label": "Send Your Response →",
        "answer_box": "You're generally entitled to ask a collection agency to verify the debt in writing before you're required to respond further. Request that in writing, keep a copy, and don't confirm the debt is yours until you've seen the verification.",
        "steps": [
            ("Don't confirm or pay before verifying", "Paying, or even confirming details verbally, can restart a debt's statute of limitations clock in some provinces. Get verification first."),
            ("Request written verification of the debt", "Ask for the original creditor's name, the amount, and the basis for the debt. Collection agencies are generally required to provide this on request."),
            ("Send your request in writing, by mail", "A mailed letter creates a dated record, stronger than a phone call, that you formally requested verification."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the collection agency's address, and attach your signed letter."),
        ],
        "warn": ("This isn't legal advice.", "Rules around debt collection and limitation periods vary by province. If the amount is significant or you're being threatened or harassed, consider speaking with a paralegal or lawyer."),
        "sections": [],
        "faq": [
            ("Do I have to pay right away?", "No. You're entitled to request verification of the debt first, and shouldn't feel pressured into immediate payment before confirming it's valid and accurately calculated."),
            ("What if the debt isn't mine?", "State that clearly in writing and request they cease contact or provide documentation proving otherwise. Keep a copy of your letter."),
            ("Can a collection agency contact me at any hour?", "No, most provinces regulate when and how often collection agencies can contact you. If you're being harassed, that's worth documenting separately."),
            ("How much does it cost to mail my response?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/dispute-credit-report-error", "Dispute a Credit Report Error", "Fix an incorrect item on Equifax or TransUnion"), ("/cease-and-desist-letter", "Cease and Desist Letter", "Put unwanted conduct on notice"), ("/demand-letter-unpaid-invoice", "Demand Letter for an Unpaid Invoice", "Get an overdue invoice paid")],
        "cta_h2": "Ready to send your response?",
        "cta_p": "Upload your letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Letter, $10 CAD →",
    },
    {
        "slug": "dispute-credit-report-error",
        "title": "Dispute a Credit Report Error by Mail (Equifax & TransUnion) | Letterhome",
        "meta_desc": "A loan you never took out, sitting on your Equifax or TransUnion report. Here's exactly how to dispute it by mail, and what to include in the envelope.",
        "service_name": "Credit Report Dispute Mailing",
        "breadcrumb": "Dispute a Credit Report Error",
        "eyebrow": "Equifax & TransUnion",
        "h1_main": "Something's wrong on your report.",
        "h1_em": "Dispute it in writing.",
        "hero_sub": "Both Equifax Canada and TransUnion Canada accept written disputes by mail. Here's what to include, and how to mail it from anywhere.",
        "cta_label": "Send Your Dispute →",
        "answer_box": "Identify the specific item you're disputing, explain why it's wrong, and include supporting documents if you have them. Both bureaus are required to investigate a written dispute within a set timeframe.",
        "steps": [
            ("Get a copy of your credit report", "Both Equifax Canada and TransUnion Canada let you request a free report. Confirm exactly which item is wrong before writing your dispute."),
            ("Write the dispute letter", "Identify the account or item, explain the error clearly, and attach any supporting documentation, like a payment record or police report for identity theft."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the correct bureau's dispute mailing address, and attach your letter and documents."),
            ("We mail it the next business day", "Your dispute goes out via Canada Post with a valid Canadian mailing date, useful if the investigation timeline is ever in question."),
        ],
        "warn": None,
        "sections": [],
        "faq": [
            ("How long does a credit bureau have to investigate?", "Both bureaus are generally required to investigate within a set number of days of receiving your written dispute. Check the current timeline on the bureau's own site."),
            ("Do I need to dispute with both Equifax and TransUnion?", "If the error appears on both reports, yes, they operate independently and don't automatically share dispute outcomes."),
            ("What if the dispute is denied?", "You can request the bureau add a statement of dispute to your file, and in some cases escalate to a provincial or federal regulator, depending on the nature of the error."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [("/respond-to-debt-collection-letter", "Responding to a Debt Collection Letter", "The calm, correct way to respond"), ("/demand-letter-unpaid-invoice", "Demand Letter for an Unpaid Invoice", "Get an overdue invoice paid"), REL_REG],
        "cta_h2": "Ready to send your dispute?",
        "cta_p": "Upload your letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Dispute, $10 CAD →",
    },
    {
        "slug": "resignation-letter-by-mail",
        "title": "Write and Mail a Resignation Letter in Canada | Letterhome",
        "meta_desc": "How much notice you actually owe, what a resignation letter needs to say, and how to mail it properly if you want a dated, physical record on file.",
        "service_name": "Resignation Letter Mailing",
        "breadcrumb": "Resignation Letter",
        "eyebrow": "Employment Correspondence",
        "h1_main": "Resigning?",
        "h1_em": "Skip the speech, keep the record.",
        "hero_sub": "A resignation letter doesn't need to be long. It needs the right lines and a date. Mailing a copy alongside handing it in person creates a record that doesn't depend on anyone forwarding an email.",
        "cta_label": "Send Your Resignation Letter →",
        "answer_box": "State your position, your last working day, and keep the tone neutral. How much notice you owe depends on your employment contract and provincial employment standards, not a universal rule.",
        "steps": [
            ("Check your notice obligations", "Your employment contract may specify a notice period. Provincial employment standards set minimums that can apply if your contract doesn't."),
            ("Write a short, neutral letter", "Your position, your last working day, and a simple statement of resignation. No need to explain your reasons in writing unless you want to."),
            ("Mail a copy for your own record", "Handing a copy to your manager is normal, mailing one as well creates a dated, independent record that you gave notice."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter your employer's mailing address, and attach your signed letter."),
        ],
        "warn": None,
        "sections": [],
        "faq": [
            ("How much notice do I actually owe?", "Check your employment contract first, then your province's employment standards minimums if the contract doesn't specify. There's no single national rule."),
            ("Do I need to explain why I'm resigning?", "No. A resignation letter can simply state the fact and your last day, an explanation is optional and not required."),
            ("Why mail a copy if I already handed one in?", "It creates a dated, independent record outside your workplace's own files, useful if a dispute ever arises about when notice was given."),
            ("How much does it cost to mail?", "$10 CAD for a domestic Canadian address, covering printing, postage, and mailing."),
        ],
        "related": [REL_CRA, ("/mail-transcripts-and-student-documents", "Mail Student Documents", "Transcripts and academic records by mail"), REL_TRACK],
        "cta_h2": "Ready to send it?",
        "cta_p": "Upload your resignation letter and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Letter, $10 CAD →",
    },
    {
        "slug": "love-letters-and-personal-mail",
        "title": "Send Love Letters, Cards & Personal Mail to Canada Online | Letterhome",
        "meta_desc": "A birthday card, a long letter to a grandparent, a note that means more on paper than in a text. Here's how to write and send personal mail to Canada from anywhere.",
        "service_name": "Personal Mail",
        "breadcrumb": "Love Letters and Personal Mail",
        "eyebrow": "Letters Home",
        "h1_main": "Some things read better",
        "h1_em": "printed, folded, and mailed.",
        "hero_sub": "A text disappears in a scroll. A letter sits on a counter, gets reread, gets kept. Here's how to send one to family or someone you love in Canada, from wherever you are.",
        "cta_label": "Write a Letter →",
        "answer_box": "You don't need a Canadian address, a printer, or a stamp. Write it, or attach a photo and a note as a PDF, and it's printed and mailed from inside Canada, arriving as a real envelope in a real mailbox.",
        "steps": [
            ("Write what you actually want to say", "Type it directly, or write it by hand and photograph or scan it as a PDF. Either works."),
            ("Add a photo if you want", "Attach up to 5 files, a printed photo alongside a letter is a common way people use this for family back home."),
            ("Send it", "Go to <a href=\"/send\">/send</a>, enter the recipient's address, and we print and mail it from Canada within one business day."),
        ],
        "warn": None,
        "sections": [
            ("Why it works for family who don't do email", [
                "Older relatives who don't check email or don't want to learn a new app still open physical mail. If someone back home reads letters better than screens, this reaches them the way they actually want to be reached.",
            ]),
        ],
        "faq": [
            ("Can I send this without a return address?", "Yes, if you'd rather keep it anonymous, we support sending <a href=\"/send-a-letter-to-canada-without-a-return-address\">without a return address</a>."),
            ("Can I include a printed photo?", "Yes, attach it as an image file alongside your letter, up to 5 attachments per order."),
            ("Does it need to be typed?", "No, handwrite it and scan or photograph it as a PDF if you'd rather send it in your own handwriting."),
            ("How much does it cost?", "$10 CAD to a Canadian address, $20 CAD anywhere else in the world."),
        ],
        "related": [REL_NORETURN, ("/mail-to-retirement-and-nursing-homes", "Mail to Retirement & Nursing Homes", "Sending letters to a loved one in care"), REL_ABROAD],
        "cta_h2": "Someone's waiting to hear from you.",
        "cta_p": "Write it in a few minutes, we'll get it there.",
        "cta_final": "Send a Letter, From $10 CAD →",
    },
    {
        "slug": "mail-transcripts-and-student-documents",
        "title": "Mail Transcripts & Student Documents in Canada | Letterhome",
        "meta_desc": "Universities and colleges often still require official transcripts and application documents by mail. Here's how to send them from anywhere.",
        "service_name": "Student Documents Mailing",
        "breadcrumb": "Student Documents & Transcripts",
        "eyebrow": "Academic Mail",
        "h1_main": "Transcripts, applications,",
        "h1_em": "mailed from Canada.",
        "hero_sub": "Some institutions still require a physical, often sealed, transcript or application document by mail. Here's how to get yours there from wherever you are.",
        "cta_label": "Send My Documents →",
        "answer_box": "Whether it's a transcript request, a supplementary application document, or a scholarship form, if the receiving institution wants paper, we print and mail it from inside Canada within one business day.",
        "steps": [
            ("Confirm what the institution requires", "Some transcripts need to arrive in a sealed envelope directly from the issuing school to be considered official, check with the receiving institution before choosing this route."),
            ("Prepare your PDF", "Export your document, application form, or cover letter as a PDF. Sign anywhere a signature is required."),
            ("Upload it at Letterhome", "Go to <a href=\"/send\">/send</a>, enter the school or program's mailing address, and attach your PDF."),
            ("We mail it the next business day", "Your document goes out via Canada Post with a valid Canadian mailing date and a confirmation email as your record."),
        ],
        "warn": ("Sealed transcripts need to come from the issuer.", "If your target school requires an official transcript sealed directly by your previous institution, that has to be requested from the issuing school itself, not mailed by a third party. This service is for application materials, cover letters, and documents you're sending yourself."),
        "sections": [],
        "faq": [
            ("Can you mail an official sealed transcript for me?", "No, an official sealed transcript needs to come directly from the issuing institution. We're the right tool for application forms, supplementary documents, and anything you're personally sending."),
            ("Can I attach multiple documents in one order?", "Yes, up to 5 files per order."),
            ("Does the deadline count from the mailing date?", "Most institutions treat the postmark or received date as what matters, check the specific program's stated policy."),
            ("How much does it cost?", "$10 CAD to a Canadian address, $20 CAD internationally."),
        ],
        "related": [REL_CRA, ("/resignation-letter-by-mail", "Resignation Letter", "Write and mail a resignation letter"), REL_ABROAD],
        "cta_h2": "Ready to send your documents?",
        "cta_p": "Upload your PDF and we'll have it in the mail by tomorrow.",
        "cta_final": "Send My Documents, $10 CAD →",
    },
    {
        "slug": "mail-to-retirement-and-nursing-homes",
        "title": "Send Mail to Someone in a Retirement or Nursing Home | Letterhome",
        "meta_desc": "A letter to a grandparent in a retirement or long-term care home means more than most mail they get. Here's how to address it correctly and send one from anywhere.",
        "service_name": "Retirement Home Mail",
        "breadcrumb": "Mail to Retirement & Nursing Homes",
        "eyebrow": "Letters to Loved Ones",
        "h1_main": "A letter means more",
        "h1_em": "when it's one of the only ones they get.",
        "hero_sub": "Family in a retirement or long-term care home often get less mail than they used to, and read it more carefully because of it. Here's how to address it correctly and send one from anywhere.",
        "cta_label": "Send a Letter →",
        "answer_box": "Include the facility's full name, your person's room or unit number, and the facility's mailing address exactly as the front desk gives it. Missing the room number is the most common reason mail gets delayed inside a large facility.",
        "steps": [
            ("Get the exact mailing format from the facility", "Call the front desk or check the facility's website. Many care homes want the resident's name, then room or unit number, then the facility name and address, in a specific order."),
            ("Write your letter", "Type it, or attach a scanned handwritten letter or a printed photo alongside it, up to 5 files per order."),
            ("Send it", "Go to <a href=\"/send\">/send</a>, enter the facility's address with your person's name and room number, and we print and mail it from Canada within one business day."),
        ],
        "warn": ("Confirm the room or unit number.", "Large facilities sort internal mail by unit, a missing or outdated room number is the most common reason a letter takes longer to reach someone inside."),
        "sections": [
            ("Why it's worth the extra step", [
                "Isolation is a real issue in long-term care, and a physical letter someone can hold, reread, and show to a nurse or a neighbour lands differently than a phone call. If they're hard of hearing or don't do video calls well, this is often the better way to reach them regularly.",
            ]),
        ],
        "faq": [
            ("What if I don't know their exact room number?", "Call the facility's front desk, they can confirm the current room or unit number and the correct mailing format before you send anything."),
            ("Can I send a printed photo along with the letter?", "Yes, attach it as an image file, up to 5 attachments per order."),
            ("Can I schedule it to arrive on a specific date, like a birthday?", "Yes, add the schedule option at checkout and choose the date you want it mailed to arrive around. See our <a href=\"/schedule-a-letter-for-later\">scheduling guide</a>."),
            ("How much does it cost?", "$10 CAD to a Canadian facility, $20 CAD internationally."),
        ],
        "related": [("/love-letters-and-personal-mail", "Love Letters & Personal Mail", "Send a letter that means more than a text"), ("/schedule-a-letter-for-later", "Schedule a Letter for Later", "Time it to arrive on a specific date"), REL_NORETURN],
        "cta_h2": "They'll be glad you wrote.",
        "cta_p": "Write it in a few minutes, we'll get it there.",
        "cta_final": "Send a Letter, From $10 CAD →",
    },
    {
        "slug": "schedule-a-letter-for-later",
        "title": "Schedule a Letter to Mail on a Future Date | Letterhome",
        "meta_desc": "Want a letter to arrive around a specific date, a birthday or anniversary, instead of right away? Here's how scheduled mailing works with Letterhome.",
        "service_name": "Scheduled Letter Mailing",
        "breadcrumb": "Schedule a Letter for Later",
        "eyebrow": "Timed Delivery",
        "h1_main": "Write it now,",
        "h1_em": "mail it exactly when you want.",
        "hero_sub": "Choose a future mailing date at checkout and we'll hold your letter and mail it then, timed so it arrives close to the date that matters to you.",
        "cta_label": "Schedule a Letter →",
        "answer_box": "Write your letter now, check the schedule option, and pick the date you want it mailed. We factor in typical Canada Post delivery time so it lands close to the date you actually care about, not the date you happened to sit down and write it.",
        "steps": [
            ("Write your letter as usual", "Type it or attach a PDF, add the recipient's address, same as any other order."),
            ("Check \"Schedule for later\"", "This adds $0.63 to your order. A date picker appears for you to choose your mailing date."),
            ("Pick your date", "Choose the date you want it mailed. For a specific arrival date like a birthday, mail a few days ahead of it to account for delivery time."),
            ("We hold it and mail it on schedule", "Your letter is printed and mailed on the date you chose, going out via Canada Post from inside Canada."),
        ],
        "warn": None,
        "sections": [
            ("Good uses for scheduling", [
                "Birthdays and anniversaries where you want the letter to actually land on or near the day, not whenever you happened to write it. Also useful if you're writing several letters at once and want them staggered rather than all arriving the same week.",
            ]),
        ],
        "faq": [
            ("How far in advance can I write it?", "Write and submit it anytime, then choose your future mailing date at checkout."),
            ("Can I cancel or change the date after ordering?", "Email support@letterhome.ca with your order number as soon as possible, changes are only possible before the letter has been printed."),
            ("Will it arrive exactly on the date I choose?", "We mail on your chosen date, but Canada Post delivery time after that is standard lettermail speed, mail a few days ahead of your target date to allow for it."),
            ("How much does scheduling cost?", "An extra $0.63 on top of your base letter price."),
        ],
        "related": [("/mail-to-retirement-and-nursing-homes", "Mail to Retirement & Nursing Homes", "Time a letter to arrive on a birthday"), ("/love-letters-and-personal-mail", "Love Letters & Personal Mail", "Send a letter that means more than a text"), REL_TRACK],
        "cta_h2": "Time it right.",
        "cta_p": "Write it now, choose when it's mailed.",
        "cta_final": "Schedule a Letter, $10 CAD →",
    },
]
